### ISSUE TITLE
underscores are not valid characters in service names?

### ISSUE THREAD

**Issue by blysik** [boivie/lovebeat#11]
Web UI is working properly.  Now I'm trying to send a test heartbeat via curl:

```
$ curl -X POST http://XXX.com/api/service/test
404 page not found
```

This is from the latest linux_amd64 binary release.

**Comment by blysik** [comment]
Hrm.  So this works.  "services", not "service":

```
$ curl -X POST http://XXX.com/api/services/test
{}
```

However, this doesn't work, it appears that the url structure does not like underscores:
```
$ curl -X POST http://XXX.com/api/services/name.servce_with_underscores
404 page not found
```

**Comment by blysik** [comment]
So, original title of this issue is false.  Renaming.

**Comment by magnusbaeck** [comment]
Indeed, [the request handler setup](https://github.com/boivie/lovebeat/blob/1.0.0-rc.1/httpapi/httpapi.go#L193) limits the service names to a-z, 0-9, periods, and hyphens. Any reason for this limitation @boivie? The equivalent code for the statsd and Graphite protocols allows anything except colons.

**Comment by boivie-at-sony** [comment]
No, I can't think of any good reasons why we shouldn't allow underscores.

**Comment by boivie-at-sony** [comment]
I uploaded a PR for this simple one. I decided to validate service names by a (currently rather strict) pattern that we can relax when necessary.
