### ISSUE TITLE
[enhancement request] add a cli alert handler

### ISSUE THREAD

**Issue by blysik** [boivie/lovebeat#13]
Hi,

I would like to be able to send an alert to Alerta (https://github.com/guardian/alerta)

Perhaps we could add a cli alert hander, which allows running an arbitrary cli script, with some variables available.

**Comment by magnusbaeck** [comment]
Sounds like a very reasonable feature request. One could also imagine REST support for talking with arbitrary APIs, but we could definitely start with being able to run a program with certain environment variables set. In addition to a limited set of variables we could actually pipe the event payload to the child process to give full access to what we know about what happened.

**Comment by blysik** [comment]
REST support would be interesting, but I imagine the configuration maybe being more complicated.  Ends up being more flexible in the end however.

**Comment by mcqueenorama** [comment]
I've got a different project that's got a nice syntax for this kind of thing.  It would fit into toml too.  For each event it will a list of http requests according to the template specification in the yaml (mine is yaml but it would fit in great here as toml).  It would be a good enhancement to the webhook,  Here's a sample of some yaml that shows a simple config that can produces arbitrary simple http calls from an event, and put event data into the url:

---
- name: nexus hook
  handler: doGet
  args:
    - "http://foo/nexus/service/local/data_incremental_index/repositories/{{ .repo }}/{{ .group }}/{{ .artifact }}"
    - "http://foo/nexus/service/local/metadata/repositories/{{ .repo }}/content/{{ .group }}/{{ .artifact }}"

For each event, loop over the args sending the http calls and exec'ing the template.

**Comment by boivie** [comment]
I started with a solution where the script gets all its information as environment variables (http://lovebeat.readthedocs.org/en/latest/alerters.html#script) but I'm open to providing the viewStateChanged event (in json) as the script's stdin - and then scripts could do more with e.g. jq (https://stedolan.github.io/jq/). Let's add that if the need arises.

Thanks for the feature request, and sorry for the long wait.

**Comment by blysik** [comment]
Nice solution!  I think environment variables is a great way to do this, and common for this type of feature.
