### ISSUE TITLE
Include service name in event data sent to alerters 

### ISSUE THREAD

**Issue by jrask** [boivie/lovebeat#19]
When receiving an event today you only get the info below, but it would be great if the service name could be included as well.

We are using slack but this might also be applicable for all other alerters.

````
"aView" has changed from ERROR to OK

View Name
----------------
aView

Incident Number
----------------
#5

From State
----------------
ERROR

To State
----------------
OK
```

**Comment by boivie-at-sony** [comment]
Fixed in commit 6e23c0c2512778358b246dfcc16ae7984308eb25
