### ISSUE TITLE
Send output from log stash to lovebeat

### ISSUE THREAD

**Issue by vikas8190** [boivie/lovebeat#23]
Im trying to send output from log stash to love beat using the below configuration. However its not being received by love beat. Any help appreciated.

output {
  statsd {
    host => "localhost"
    port => 8127
    count => {
        "monitor.autobeat" => "1"
    }
    debug => true
 }
 stdout { codec => rubydebug }
}

**Comment by magnusbaeck** [comment]
This problem has been solved and turned out to be a (DNS-related?) problem on the Logstash side (https://discuss.elastic.co/t/monitor-inactivity-in-log-files/50597/9). Closing.
