### ISSUE TITLE
docker image does not contain root certificates

### ISSUE THREAD

**Issue by mkurucz** [boivie/lovebeat#28]
I am running the docker image and _slack_ alert gives the following error:
x509: failed to load system roots and no roots provided

I can bypass the problem by logging into the container and running:
apt-get update & apt-get install ca-certificates

Could you update the image with the certificates?

Thanks

**Comment by boivie** [comment]
Yes, that's a mistake.

I have pushed a new commit and new images to github.

```
boivie/lovebeat                1.0.1-2             a84ccaa35dce
boivie/lovebeat                latest              a84ccaa35dce
```

Thanks for reporting this!
