### ISSUE TITLE
Asset, AssetDir - Doesn't Build

### ISSUE THREAD

**Issue by mcqueenorama** [boivie/lovebeat#7]
Head of master doesn't build.  Maybe the Readme needs some updating.  It looks like there are some config values need in the dashboard?

L-SB831WYFD5-M:lovebeat bmcquee$ go build
# github.com/boivie/lovebeat/dashboard
dashboard/dashboard.go:56: undefined: Asset
dashboard/dashboard.go:56: undefined: AssetDir

**Comment by mcqueenorama** [comment]
I see the comments for this commit now:

https://github.com/boivie/lovebeat/commit/209933b4ad4fb6cdc0412a98af33469457b94a89

Its building.

**Comment by magnusbaeck** [comment]
Side note: `make` will take care of running all the bower etc commands (though you still need to install npm by hand).
